### ISSUE TITLE
Bump gem version?

### ISSUE THREAD

**Issue by ragaskar** [pivotal/git_scripts#27]
Hi:

Is it possible to bump the gem version? We would like to pull in the custom email feature, and it's inconvenient to do this from master vs. the gem.

**Comment by flavorjones** [comment]
Took things into my own hands. Cut 1.4.0, up on rubygems now.

**Comment by ragaskar** [comment]
FWIW, most people install from master, so I didn't bother pushing the gem when I merged the last pull.
