### ISSUE TITLE
git-pair-commit doesn't work on Windows

### ISSUE THREAD

**Issue by brunoyb** [pivotal/git_scripts#37]
On Windows the system call doesn't work, probably because of the environment variables being set before git commit (GIT_AUTHOR_NAME=name git commit). Is there any plans on making this compatible with Windows? Thanks!

**Comment by tjarratt** [comment]
Hey @brunoyb I'm sorry you didn't get an answer sooner.

We'd certainly be open to having this work on Windows, but we generally (99.99% of the time) don't do any development work on Windows at all. If you (or anyone else???) is interested in submitting a PR for this, we'd be happy to provide guidance or help.

Things we would probably want
- `git pair` should work on windows
- travis.yml should be updated to run our tests on windows 
- ???
- profit!

**Comment by mhoran** [comment]
Hey @brunoyb. I'd recommend trying out [git-duet](https://github.com/git-duet/git-duet), which works great on Windows!

**Comment by brunoyb** [comment]
Hey! I would like to try to contribute with a fix but I didn't have the time to do it yet. But I will try git-duet to see how it works. Thanks for the suggestion!

**Comment by tjarratt** [comment]
The actionable steps for fixing this bug are to make it so we set our environment variables using the ruby `ENV` class, rather than assuming we can assign them before we shell out to `git`.

[Relevant line in the project](https://github.com/pivotal/git_scripts/blob/81f510dd32cd3de8a1b720d5067c7d427289755e/lib/pivotal_git_scripts/git_pair.rb#L69)

**Comment by brunoyb** [comment]
Yes, that's what I thought, but I don't know Ruby very well so I was not sure how to do it. I will try to learn how to configure the environment so I can test the changes... Anyway, I was also thinking about using the `-c` switch of git that allow you to pass a configuration parameter to that specific command. For instance:

`git -c user.name='Name' -c user.email='email@address.com' commit`

Do you think that would work? Then we wouldn't need to rely on env variables to set author and committer.

I also looked at git-duet, it seems really nice but I don't think it will work well for us. As I understand git-duet uses the committer field for one of the contributors. The problem with that is that Gerrit (the code review tool we use) sometimes replaces the committer field with a Gerrit Author (when it has to rebase, for example). We can try to work around it, but I think git-pair is ideal for our workflow!

**Comment by grndvl1** [comment]
I like when people only think for one platform and that maybe coders might not all be using Mac or unix laptops.  As you can tell that was sarcasm.
